### ISSUE TITLE
Question about datapoint lengths

### ISSUE THREAD

**Issue by pablogranolabar** [mirkosavasta/GANetano#3]
Hey, very nice repo. Thank you for making your work available.

Question: I have been studying your code and cannot for the life of me figure out how the Critic class dimensions are being established. The Generator seems fairly straightforward, the input dimension from the sines dataset is 100 datapoints. But after attempting to modify those values in both the datasets.py and wgangp.py, I am still getting a deeply nested runtime that indicates the Critic shape is wrong. But I'm not seeing how the Critic gets its input shape?

**Comment by mirkosavasta** [comment]
If you modify the length of the latent vector that you are going to feed to the Generator, you will need to modify the Critic as well. Our layers in this case are mainly 1d convolutions. Now, to understand how your input shapes gradually become output shapes you should read about some [convolutional arithmetic](http://deeplearning.net/software/theano/tutorial/conv_arithmetic.html). After your reading, you should apply your knowledge using a google sheet to understand how shapes change inside the network (layer by layer) and see what happens when convolution parameters and input shapes change.
